-- AlterTable
ALTER TABLE `BusinessSettings`
  ADD COLUMN `accentColor` VARCHAR(191) NOT NULL DEFAULT '#7DFF7A',
  ADD COLUMN `successColor` VARCHAR(191) NOT NULL DEFAULT '#5FD46A',
  ADD COLUMN `warningColor` VARCHAR(191) NOT NULL DEFAULT '#F0B429',
  ADD COLUMN `dangerColor` VARCHAR(191) NOT NULL DEFAULT '#F04438';
